version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: carrierwave
    versions:
    - 2.1.0
    - 2.1.1
  - dependency-name: excon
    versions:
    - 0.78.1
    - 0.79.0
  - dependency-name: brakeman
    versions:
    - 5.0.0
  - dependency-name: loofah
    versions:
    - 2.9.0
